Application/WebApplicationMVCRentalOfPremises/Controllers/OutleetController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplicationMVCRentalOfPremises.Data;
using WebApplicationMVCRentalOfPremises.Infrastructure;
namespace WebApplicationMVCRentalOfPremises.Controllers
{
    public class OutleetController:Controller
    {
        private OutleetStoregeIntrafce storegeIntrafce = SeedData.OutleetStoregeIntrafce;
        [HttpGet]
        public IActionResult CreateProduct(int id)
        {
            var model=storegeIntrafce.GetModelById(id);
            if(model is null)
            {
                model=new Models.OutleetModel();
                model.ID = (int)-1;
            }
            Console.WriteLine($"model id:{model.ID}");
            return View(model);
        }
        [HttpPost]
        public IActionResult CreateProduct([Bind("ID,Storey,Area,InventoryNumber,RentalCostPerDay,PresenceOfAirConditioning,AllocatedPowerKilowatts,NumberOfWindows")]Models.OutleetModel model)
        {
            if (model.ID == -1)
            {
                if (storegeIntrafce.GetModelByInventoryNumber(model.InventoryNumber) is null == false)
                    ModelState.AddModelError(nameof(model.InventoryNumber),"Нарушена уникальность инвертарного номера");
            }
            if (ModelState.IsValid)
            {
 Console.WriteLine("succes!");
                if (model.ID == -1)
                    storegeIntrafce.AddModel(model);
                else storegeIntrafce.UpdateById(model);
                return Redirect("/Home/Index");
            }
            
               
                return 
                    View( model);
           
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteProduct(int id)
        {
            storegeIntrafce.RemoveById(id);
            return Redirect("/Home/Index");
        }
        [HttpGet]
        public IActionResult GetProduct(int id)
        {
            var mod=storegeIntrafce.GetModelById(id);
            return View(mod);
        }
        [AcceptVerbs("GET", "POST")]
        public IActionResult VerifyInventoryNumber(int InventoryNumber,int ?id)
        {
            Console.WriteLine("start validators!");
            if (( id == -1|| id is null)&&(storegeIntrafce.GetModelByInventoryNumber(InventoryNumber) is null==false))
            {
                Console.WriteLine("not valid!");
                return Json(false);
            }
            else return Json(true);
        }
        [AcceptVerbs("GET", "POST")]
        public IActionResult VerifyRentalCostPerDay(decimal RentalCostPerDay)
        {
            return Json(RentalCostPerDay > 0);
        }
    }
}

Application/WebApplicationMVCRentalOfPremises/Views/Outleet/CreateProduct.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using WebApplicationMVCRentalOfPremises.Models;
@model OutleetModel
<div class="text-center">
    <h1 class="display-2">Внесение данных о торговой точке</h1>
</div>
<form asp-controller="Outleet" method="post" asp-action="CreateProduct">
    <div class="form-control">
        <input type="hidden" asp-for="ID" value="@Model.ID" />
    </div>
    <div class="form-control">
        <label asp-for="Storey" class="form-text">Этаж:</label>
        <input type="number" asp-for="Storey" value="@Model.Storey" class="input-group"/>
        <span asp-validation-for="Storey" class="text-danger"></span>
    </div>
    <div class="form-control">
        <label asp-for="Area" class="form-text">Площадь помещения:</label>
        <input type="number" asp-for="Area" value="@Model.Area" class="input-group" />
        <span asp-validation-for="Area" class="text-danger"></span>
    </div>
    <div class="form-control">
        <label asp-for="NumberOfWindows" class="form-text">Число окон:</label>
        <input type="number" asp-for="NumberOfWindows" class="input-group" value="@Model.NumberOfWindows" />
        <span asp-validation-for="NumberOfWindows" class="text-danger"></span>
    </div>
    <div class="form-control">
        <label asp-for="PresenceOfAirConditioning" class="form-text">Кондиционер присутвует?</label>
        <input type="hidden" asp-for="PresenceOfAirConditioning" value="@Model.PresenceOfAirConditioning"  id="valpac"/>
        <span asp-validation-for="PresenceOfAirConditioning" class="text-danger"></span>
        @{
            bool stat = Model.PresenceOfAirConditioning == 1;
        }
        @{
            if (!stat)
            {
                <input type="checkbox" class="form-check"  id="inpchec" />
            }
            else
            {
                <input type="checkbox" class="form-check" id="inpchec" checked />
            }
        }
       
        <script>
            var chec=document.getElementById("inpchec");
            var pac = document.getElementById("valpac");
            chec.onchange = () => {
                if (chec.checked) {
                    pac.value = "1";
                } else {
                    pac.value = "0";
                }
            }
        </script>

    </div>
    <div class="form-control">
        <label asp-for="AllocatedPowerKilowatts" class="form-text">
            Число выделенных киловат:
        </label>
        <input type="number" asp-for="AllocatedPowerKilowatts" value="@Model.AllocatedPowerKilowatts" class="input-group" />
        <span asp-validation-for="AllocatedPowerKilowatts" class="text-danger"></span>
    </div>
    <div class="form-control">
        <label asp-for="InventoryNumber" class="form-text">
            Инвертарный номер
        </label>
        <input type="number" asp-for="InventoryNumber" value="@Model.InventoryNumber" class="input-group" />
        <span asp-validation-for="InventoryNumber" class="text-danger"></span>
    </div>
    <div class="form-control">
        <label asp-for="RentalCostPerDay" class="form-text">Стоимость аренды в день</label>
        <input type="number" asp-for="RentalCostPerDay" value="@Model.RentalCostPerDay" class="input-group" />
        <span asp-validation-for="RentalCostPerDay" class="text-danger"></span>
    </div>

    <div class="form-control">
        <button type="submit" class="btn btn-info">Сохранить</button>
    </div>
   

</form>
<!--
/*
https://learn.microsoft.com/ru-ru/aspnet/core/tutorials/first-mvc-app/validation?view=aspnetcore-9.0
https://learn.microsoft.com/ru-ru/aspnet/core/mvc/models/validation?view=aspnetcore-9.0
*/
-->

Application/WebApplicationMVCRentalOfPremises/Views/Outleet/GetProduct.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model OutleetModel?
@{
    if(Model is null)
    {
        <strong>Отсутвует указааная позиция</strong>
        return;
    }
}
<h2 class="display-3">Подробная информация</h2>
<div class="container">
    <div class="row">
        <div class="col">
            Инвертаный номер:
        </div>
        <div class="col">
            <i>
                @Model.InventoryNumber
            </i>
        </div>
    </div>
    @{
        var values = new object[]
          {
          Model.InventoryNumber,Model.NumberOfWindows,Model.AllocatedPowerKilowatts,
          Model.Storey,Model.Area,Model.RentalCostPerDay,(Model.PresenceOfAirConditioning==1?"Присутвует":"Отсутвует")
          };
        var names = new string[]
        {
            "Инвертарный номер","Число окон","Число выделенных киловатт",
            "Этаж","Площадь помещения","Стоимость аренды в день","Наличие кондиционера"
        };
        for(int i = 0; i < values.Count(); i++)
        {
           <div class="row">
               <div class="col">
               @names[i]
               </div>
               <div class="col">
                   :<i>@values[i]</i>
               </div>
           </div>
        }
    }
</div>